image: node:lts-alpine

variables:
  CI_REGISTRY_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - registry

install dependencies:
  stage: build
  script:
    - npm install --progress=false

check linter:
  stage: lint
  script:
    - npm run lint:check

docker registry image:
  stage: registry
  image: docker:git
  services:
    - docker:dind
  script:
    - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://gcr.io
    - docker build --cache-from -t gcr.io/$GCP_PROJECT_ID/$GCP_PROJECT_NAME:latest -t $GCP_REGISTRY_IMAGE:latest .
    - docker push gcr.io/$GCP_PROJECT_ID/$GCP_PROJECT_NAME:latest
  environment:
    name: ${CI_COMMIT_REF_NAME}
  only:
    - develop
    - main
